server:
  port: 10010

# 服务名称
spring:
  application:
    name: gateway

# nacos的地址
  cloud:
    nacos:
      server-addr: localhost:8848
    # server-addr: localhost:8888 # nginx的监听端口
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice # 路由的目前地址
          predicates: # 路由断言：判断请求是否符合规则
            - Path=/user/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=Truth, Javadong will be a member of Tecent cooperation.
